### PR TITLE
Bukkit API 14 compatibility

### PR DESCRIPTION
**Pull request by nadiamoe**
Works on my ~~machine~~ server.

TODO:
* [ ] Check if any new entities were added in this new version of the API. Just commented out those no longer present.
* [ ] Implement a workaround to prevent chunk unloading, if possible. For now, it just prints a warning.

### CODE REVIEW

**Comment by C4K3** [comment]
Thanks for this PR! I'll try to take a look at it ASAP. If I haven't responded in 1 week feel free to ping me again :-)

@Melvin3000 could you take a look?

**Comment by nadiamoe** [comment]
NP, thanks to you for the effort put on this plugin :D
About the chunk unloading thing, I have two concerns:
1. Why is it there at the first place? Is it related to nearby entities teleporting, or to the sendBlockChange hack?
2. The method got removed in 1.14 but there is still a [`setSaveChunk(boolean)`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/world/ChunkUnloadEvent.html#setSaveChunk-boolean-). Bukkit javadoc is not very verbose so I'm not sure if this could act as a replacement (don't save to disk meaning "keep in memory", therefore cancelling the unload) or if it is an entirely different thing (don't save to disk meaning "send it to the void")

**Comment by nadiamoe** [comment]
Any news on this?

**Comment by C4K3** [comment]
Hi, very sorry for not responding, got caught up in other stuff.

This PR looks fine, from what I can tell the chunk unloading preventing was to try to prevent an instant death bug, but testing locally I was not able to reproduce it even without preventing the chunk unloading.

**Comment by C4K3** [comment]
I opened #11 to remember to check for new entities :)

**Pull request merged**
